/* Code generated by "ordnat". DO NOT EDIT. */
#ifndef __JOINTMESH_H__
#define __JOINTMESH_H__

#include <stdlib.h>
#include <stdint.h>
#include "math.h"
#include <stdio.h>

/* mesh structure with joint memory allocation */
struct joint_mesh {
  Vector3 *positions;
  int *indices;
  Vector2 *uvs;

  void *memory_block;
  int array_count;
  int32_t offset[3];
};

static inline struct joint_mesh alloc_joint_mesh(void *(*mem_allocator)(size_t), size_t n_positions, size_t n_indices, size_t n_uvs) {
  int32_t current_offset = 0;
  struct joint_mesh data = { 0 };
  data.array_count = 3;

  current_offset += ((sizeof(Vector3)) * (n_positions));
  data.offset[0] = current_offset;

  current_offset += ((sizeof(int)) * (n_indices));
  data.offset[1] = current_offset;

  current_offset += ((sizeof(Vector2)) * (n_uvs));
  data.offset[2] = current_offset;

  data.memory_block = mem_allocator(current_offset);

  data.positions = (Vector3 *)(data.memory_block);
  data.indices = (int *)((char *)(data.memory_block) + (data.offset[0]));
  data.uvs = (Vector2 *)((char *)(data.memory_block) + (data.offset[1]));

  return data;
}

#endif /* __JOINTMESH_H__ */
