# This is a TOML document.
[header]
lib = ['"math.h"', '<stdio.h>']

[data]
mesh = [
  { type = "Vector3", name = "position" },
  { type = "int", name = "index" },
  { type = "Vector2", name = "uv" }
]

foo = []
