# This is a TOML document.
[header]
lib = ['"math.h"', '<stdio.h>']

[data]
mesh = [
  { type = "Vector3", name = "position", count = "10" },
  { type = "int", name = "index", count = "20" },
  { type = "Vector2", name = "uv", count = "10" }
]

foo = []
